### PR TITLE
Add perl and tailwindcss support.

### PR DESCRIPTION
**Pull request by PerilousBooklet**

### CODE REVIEW

**Comment by jgmdev** [comment]
About tailwind, what do you mean by new json.lua? https://github.com/rxi/json.lua hasn't seen any commits for around 4 years. Is there some fork I should look at?

**Comment by PerilousBooklet** [comment]
Me and Guldoman tried tailwindcss with `lite-xl-lsp` and it freezes when you start writing class names. Guldoman observed an enourmous amount of data being sent from the tailwindcss server to lite-xl and said (if I remember correctly) that the freeze could be solved by re-implementing something related to json and lua.
Actually I'm not sure, as I'm a beginner when it comes to lite-xl internals.

**Comment by PerilousBooklet** [comment]
Ok, I just consulted Guldoman and he says that a new C implementation of the json lib is needed because `tailwindcss` sends MBs to lite-xl-lsp, slowing it down.

**Comment by jgmdev** [comment]
Thanks for the explanation, also you should adjust your perlnavigator addition to look like this https://github.com/pragtical/lsp/commit/5082ffda6f26291eac526103bf577ddd3f300883 basically the same patter as the other entries on config.lua

**Comment by PerilousBooklet** [comment]
I have a request regarding this PR: I made a mistake in setting up this PR, because I didn't create a branch specific to the perl/tailwind addition and now that I want to add the R language I can't avoid mixing commits and making a mess.
My request is to accept (if the PR is acceptable) this PR so that I can update the master branch and create the proper new branch for adding R support.

**Comment by Guldoman** [comment]
Thank you!

**Pull request merged**
